# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Group'),
        ),
    ]
