# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0002_auto_20161005_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='group',
            name='group_ID',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='main_subscriber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_ID',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='reservation_ID',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
