# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0003_auto_20161005_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
