# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0004_participant_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
