# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0005_auto_20161005_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='villager',
            name='familiars',
            field=models.ManyToManyField(related_name='_villager_familiars_+', to='Autospelleider.Villager'),
        ),
        migrations.AddField(
            model_name='villager',
            name='participant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Participant'),
        ),
    ]
