# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0006_auto_20161005_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villager',
            name='familiars',
            field=models.ManyToManyField(blank=True, related_name='_villager_familiars_+', to='Autospelleider.Villager'),
        ),
        migrations.AlterField(
            model_name='villager',
            name='participant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Autospelleider.Participant'),
        ),
    ]
