# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0007_auto_20161005_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AddField(
            model_name='villager',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
    ]
