# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0008_auto_20161005_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='village_ID',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
