# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0009_village_village_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='familiar_groups',
            field=models.ManyToManyField(blank=True, related_name='_group_familiar_groups_+', to='Autospelleider.Group'),
        ),
    ]
