# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0010_group_familiar_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='start_inhabitants',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
