# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0011_village_start_inhabitants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('done', models.BooleanField(default=False)),
                ('purpose', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='village',
            name='timer_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='villager',
            name='role',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
