# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0012_auto_20161007_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='villager',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
