# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0013_villager_alive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='done',
        ),
        migrations.RemoveField(
            model_name='village',
            name='timer_on',
        ),
        migrations.AddField(
            model_name='timer',
            name='not_done',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timer',
            name='village',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Autospelleider.Village'),
        ),
    ]
