# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0014_auto_20161008_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='village',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timer', to='Autospelleider.Village'),
        ),
    ]
