# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0015_auto_20161009_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='village',
        ),
        migrations.AddField(
            model_name='village',
            name='timer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='village_timer', to='Autospelleider.Timer'),
        ),
    ]
