# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0018_auto_20161010_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='influences',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='start_characters',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='start_characters_amounts',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
