# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0019_auto_20161010_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auraziener',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='bezweerder',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='bodyguard',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='cupido',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='dorpeling',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='dronkaard',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='dubbelganger',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='eenzamewolf',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='heks',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='jager',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='leerlingziener',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='looier',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='magier',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='martelares',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='medium',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='onruststoker',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='oudeman',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='oudwijf',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='priester',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='prins',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='schurk',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='sekteleider',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='stoerekerel',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='tovenares',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='vampier',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='vervloekte',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='volgeling',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='vrijmetselaar',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='weerwolf',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='welp',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='wolfmens',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='zieke',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
        migrations.AlterField(
            model_name='ziener',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village'),
        ),
    ]
