# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0020_auto_20161010_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='villager',
            name='seat',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
