# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0022_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='creation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='textinfo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
