# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0023_auto_20161014_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
