# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0024_notification_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='todo', max_length=200),
        ),
    ]
