# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0027_auto_20161017_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_ID', models.PositiveIntegerField()),
                ('amount_paid', models.PositiveIntegerField()),
                ('voorverkoop', models.BooleanField()),
                ('completed', models.BooleanField()),
                ('creation_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('leeftijd', models.PositiveIntegerField()),
                ('participant_ID', models.PositiveIntegerField(null=True)),
                ('main_subscriber', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Group')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Autospelleider.Reservation')),
            ],
        ),
    ]
