# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0028_reservation_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='amount_paid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='creation_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_ID',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
