# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0029_auto_20161026_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Autospelleider.Reservation'),
        ),
    ]
