# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0030_auto_20161026_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='voorverkoop',
            field=models.BooleanField(default=False),
        ),
    ]
