# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 13:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0034_auto_20161108_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='leeftijd',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='participant_ID',
        ),
        migrations.AddField(
            model_name='subscription',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 8, 13, 39, 1, 555251)),
        ),
    ]
