# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 13:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0035_auto_20161108_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 8, 13, 50, 46, 674581)),
        ),
    ]
