# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 16:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0036_auto_20161108_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_ID',
        ),
        migrations.AddField(
            model_name='group',
            name='group_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 8, 16, 52, 38, 92679)),
        ),
    ]
