# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autospelleider', '0046_auto_20161108_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(blank=True, max_length=200, null=True)),
                ('group_ID', models.IntegerField(blank=True, default=-1, null=True)),
                ('familiar_groups', models.ManyToManyField(blank=True, related_name='_groupsubscription_familiar_groups_+', to='Autospelleider.GroupSubscription')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autospelleider.Village')),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 11, 18, 45, 26, 128287)),
        ),
    ]
